<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../BarberTurn.Application/BarberTurn.Application.csproj" />
    <ProjectReference Include="../BarberTurn.Infrastructure/BarberTurn.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.*" />
  </ItemGroup>
</Project>
