import type { Dictionary } from './types';

type AfricaLocale = 'ar' | 'sw' | 'af' | 'am' | 'so' | 'ha' | 'yo' | 'ig' | 'zu' | 'xh';

const make = (values: Partial<Dictionary>): Dictionary => values as Dictionary;

export const africaWave1Mobile: Record<AfricaLocale, Dictionary> = {
  ar: make({ 'login.title':'صالون الحلاقة الخاص بك، في جيبك أيضًا.','login.email':'البريد الإلكتروني','login.password':'كلمة المرور','login.invalidCredentials':'البريد الإلكتروني أو كلمة المرور غير صحيحة.','login.failed':'تعذر تسجيل الدخول.','login.submitting':'جارٍ تسجيل الدخول…','login.submit':'تسجيل الدخول','home.hello':'مرحبًا، {{name}}.','home.team':'الفريق','home.requests':'طلبات الدور','home.requestsText':'إدارة الطلبات المعلقة واستلام التحديثات في الوقت الفعلي.','home.pushTitle':'لا تفوّت أي طلب جديد','home.signOut':'تسجيل الخروج','push.enabledTitle':'تم تفعيل الإشعارات','push.enabledBody':'سيتلقى هذا الجهاز التحديثات المهمة.','push.enabling':'جارٍ التفعيل…','push.enable':'تفعيل الإشعارات' }),
  sw: make({ 'login.title':'Kinyozi chako, pia mfukoni mwako.','login.email':'Barua pepe','login.password':'Nenosiri','login.invalidCredentials':'Barua pepe au nenosiri si sahihi.','login.failed':'Hatukuweza kukuingiza.','login.submitting':'Inaingia…','login.submit':'Ingia','home.hello':'Habari, {{name}}.','home.team':'timu','home.requests':'Maombi ya zamu','home.requestsText':'Dhibiti maombi yanayosubiri na upokee masasisho ya papo hapo.','home.pushTitle':'Usikose ombi jipya','home.signOut':'Toka','push.enabledTitle':'Arifa zimewashwa','push.enabledBody':'Kifaa hiki kitapokea masasisho muhimu.','push.enabling':'Inawasha…','push.enable':'Washa arifa' }),
  af: make({ 'login.title':'Jou barbershop, ook in jou sak.','login.email':'E-pos','login.password':'Wagwoord','login.invalidCredentials':'Verkeerde e-pos of wagwoord.','login.failed':'Ons kon jou nie aanmeld nie.','login.submitting':'Meld aan…','login.submit':'Meld aan','home.hello':'Hallo, {{name}}.','home.team':'span','home.requests':'Beurtversoeke','home.requestsText':'Bestuur hangende versoeke en ontvang intydse opdaterings.','home.pushTitle':'Moenie nuwe versoeke misloop nie','home.signOut':'Meld af','push.enabledTitle':'Kennisgewings geaktiveer','push.enabledBody':'Hierdie toestel sal belangrike opdaterings ontvang.','push.enabling':'Aktiveer…','push.enable':'Aktiveer kennisgewings' }),
  am: make({ 'login.title':'የእርስዎ ፀጉር ቤት፣ በኪስዎ ውስጥም።','login.email':'ኢሜይል','login.password':'የይለፍ ቃል','login.failed':'መግባት አልተቻለም።','login.submit':'ግባ','home.hello':'ሰላም፣ {{name}}።','home.team':'ቡድን','home.requests':'የተራ ጥያቄዎች','home.signOut':'ውጣ','push.enabledTitle':'ማሳወቂያዎች ነቅተዋል','push.enable':'ማሳወቂያዎችን አንቃ' }),
  so: make({ 'login.title':'Timo-jarahaaga, jeebkaagana ku jira.','login.email':'Iimayl','login.password':'Furaha sirta','login.invalidCredentials':'Iimayl ama furaha sirta waa khalad.','login.failed':'Ma awoodin inaan ku galino.','login.submit':'Gal','home.hello':'Salaan, {{name}}.','home.team':'koox','home.requests':'Codsiyada safka','home.signOut':'Ka bax','push.enabledTitle':'Ogeysiisyadu way shaqaynayaan','push.enable':'Daar ogeysiisyada' }),
  ha: make({ 'login.title':'Shagon askinka, har cikin aljihunka.','login.email':'Imel','login.password':'Kalmar sirri','login.invalidCredentials':'Imel ko kalmar sirri ba daidai ba ne.','login.failed':'Ba mu iya shigar da kai ba.','login.submit':'Shiga','home.hello':'Sannu, {{name}}.','home.team':'ƙungiya','home.requests':'Buƙatun layi','home.signOut':'Fita','push.enabledTitle':'An kunna sanarwa','push.enable':'Kunna sanarwa' }),
  yo: make({ 'login.title':'Ilé ìrun rẹ, tún wà nínú àpò rẹ.','login.email':'Ímeèlì','login.password':'Ọ̀rọ̀ aṣínà','login.invalidCredentials':'Ímeèlì tàbí ọ̀rọ̀ aṣínà kò tọ́.','login.failed':'A kò le wọlé fún ọ.','login.submit':'Wọlé','home.hello':'Pẹ̀lẹ́, {{name}}.','home.team':'ẹgbẹ́','home.requests':'Àwọn ìbéèrè ìlà','home.signOut':'Jáde','push.enabledTitle':'Àwọn ìfitónilétí ti ṣiṣẹ́','push.enable':'Mú ìfitónilétí ṣiṣẹ́' }),
  ig: make({ 'login.title':'Ụlọ ịkpụ isi gị, dịkwa n’akpa gị.','login.email':'Email','login.password':'Okwuntughe','login.invalidCredentials':'Email ma ọ bụ okwuntughe ezighi ezi.','login.failed':'Anyị enweghị ike ibanye gị.','login.submit':'Banye','home.hello':'Ndewo, {{name}}.','home.team':'otu','home.requests':'Arịrịọ ahịrị','home.signOut':'Pụọ','push.enabledTitle':'Agbanyere ọkwa','push.enable':'Gbanye ọkwa' }),
  zu: make({ 'login.title':'I-barbershop yakho, nayo ephaketheni lakho.','login.email':'I-imeyili','login.password':'Iphasiwedi','login.invalidCredentials':'I-imeyili noma iphasiwedi ayilungile.','login.failed':'Asikwazanga ukukungenisa.','login.submit':'Ngena','home.hello':'Sawubona, {{name}}.','home.team':'ithimba','home.requests':'Izicelo zomugqa','home.signOut':'Phuma','push.enabledTitle':'Izaziso zivuliwe','push.enable':'Vula izaziso' }),
  xh: make({ 'login.title':'I-barbershop yakho, nayo epokothweni lakho.','login.email':'I-imeyile','login.password':'Igama lokugqitha','login.invalidCredentials':'I-imeyile okanye igama lokugqitha alichanekanga.','login.failed':'Asikwazanga ukukungenisa.','login.submit':'Ngena','home.hello':'Molo, {{name}}.','home.team':'iqela','home.requests':'Izicelo zomgca','home.signOut':'Phuma','push.enabledTitle':'Izaziso zivuliwe','push.enable':'Vula izaziso' }),
};
