import type { Dictionary } from './types';

export const asiaWave2Mobile: Record<string, Dictionary> = {
  ta: { 'login.title': 'உங்கள் பார்பர்ஷாப், உங்கள் கையில்.', 'login.email': 'மின்னஞ்சல்', 'login.password': 'கடவுச்சொல்', 'login.submit': 'உள்நுழைக', 'home.hello': 'வணக்கம், {{name}}.', 'home.requests': 'வரிசை கோரிக்கைகள்', 'home.signOut': 'வெளியேறு', 'push.enable': 'அறிவிப்புகளை இயக்கு' },
  te: { 'login.title': 'మీ బార్బర్‌షాప్, మీ చేతిలోనే.', 'login.email': 'ఇమెయిల్', 'login.password': 'పాస్‌వర్డ్', 'login.submit': 'సైన్ ఇన్', 'home.hello': 'హలో, {{name}}.', 'home.requests': 'టర్న్ అభ్యర్థనలు', 'home.signOut': 'సైన్ అవుట్', 'push.enable': 'నోటిఫికేషన్లు ప్రారంభించండి' },
  mr: { 'login.title': 'तुमचे बार्बरशॉप, तुमच्या हातात.', 'login.email': 'ईमेल', 'login.password': 'पासवर्ड', 'login.submit': 'साइन इन', 'home.hello': 'नमस्कार, {{name}}.', 'home.requests': 'टर्न विनंत्या', 'home.signOut': 'साइन आउट', 'push.enable': 'सूचना सुरू करा' },
  gu: { 'login.title': 'તમારું બાર્બરશોપ, તમારા હાથમાં.', 'login.email': 'ઇમેઇલ', 'login.password': 'પાસવર્ડ', 'login.submit': 'સાઇન ઇન', 'home.hello': 'નમસ્તે, {{name}}.', 'home.requests': 'ટર્ન વિનંતીઓ', 'home.signOut': 'સાઇન આઉટ', 'push.enable': 'સૂચનાઓ ચાલુ કરો' },
  pa: { 'login.title': 'ਤੁਹਾਡਾ ਬਾਰਬਰਸ਼ਾਪ, ਤੁਹਾਡੇ ਹੱਥ ਵਿੱਚ.', 'login.email': 'ਈਮੇਲ', 'login.password': 'ਪਾਸਵਰਡ', 'login.submit': 'ਸਾਇਨ ਇਨ', 'home.hello': 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ, {{name}}.', 'home.requests': 'ਟਰਨ ਬੇਨਤੀਆਂ', 'home.signOut': 'ਸਾਇਨ ਆਉਟ', 'push.enable': 'ਸੂਚਨਾਵਾਂ ਚਾਲੂ ਕਰੋ' },
  kn: { 'login.title': 'ನಿಮ್ಮ ಬಾರ್ಬರ್‌ಶಾಪ್, ನಿಮ್ಮ ಕೈಯಲ್ಲೇ.', 'login.email': 'ಇಮೇಲ್', 'login.password': 'ಪಾಸ್‌ವರ್ಡ್', 'login.submit': 'ಸೈನ್ ಇನ್', 'home.hello': 'ನಮಸ್ಕಾರ, {{name}}.', 'home.requests': 'ಟರ್ನ್ ವಿನಂತಿಗಳು', 'home.signOut': 'ಸೈನ್ ಔಟ್', 'push.enable': 'ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ' },
  ml: { 'login.title': 'നിങ്ങളുടെ ബാർബർഷോപ്പ്, നിങ്ങളുടെ കൈയിൽ.', 'login.email': 'ഇമെയിൽ', 'login.password': 'പാസ്‌വേഡ്', 'login.submit': 'സൈൻ ഇൻ', 'home.hello': 'നമസ്കാരം, {{name}}.', 'home.requests': 'ടേൺ അഭ്യർത്ഥനകൾ', 'home.signOut': 'സൈൻ ഔട്ട്', 'push.enable': 'അറിയിപ്പുകൾ പ്രവർത്തനക്ഷമമാക്കുക' },
  ne: { 'login.title': 'तपाईंको बार्बरशप, तपाईंको हातमै।', 'login.email': 'इमेल', 'login.password': 'पासवर्ड', 'login.submit': 'साइन इन', 'home.hello': 'नमस्ते, {{name}}.', 'home.requests': 'टर्न अनुरोधहरू', 'home.signOut': 'साइन आउट', 'push.enable': 'सूचनाहरू सक्रिय गर्नुहोस्' },
  si: { 'login.title': 'ඔබේ බාබර්ශොප් එක, ඔබේ අතේම.', 'login.email': 'ඊමේල්', 'login.password': 'මුරපදය', 'login.submit': 'පිවිසෙන්න', 'home.hello': 'ආයුබෝවන්, {{name}}.', 'home.requests': 'වාර ඉල්ලීම්', 'home.signOut': 'පිටවන්න', 'push.enable': 'දැනුම්දීම් සක්‍රිය කරන්න' },
  my: { 'login.title': 'သင့်ဘာဘာဆိုင်ကို လက်ထဲမှာပဲ အသုံးပြုပါ။', 'login.email': 'အီးမေးလ်', 'login.password': 'စကားဝှက်', 'login.submit': 'ဝင်မည်', 'home.hello': 'မင်္ဂလာပါ {{name}}။', 'home.requests': 'အလှည့်တောင်းဆိုမှုများ', 'home.signOut': 'ထွက်မည်', 'push.enable': 'အသိပေးချက်များ ဖွင့်မည်' },
  km: { 'login.title': 'ហាងកាត់សក់របស់អ្នក នៅក្នុងដៃអ្នក។', 'login.email': 'អ៊ីមែល', 'login.password': 'ពាក្យសម្ងាត់', 'login.submit': 'ចូល', 'home.hello': 'សួស្តី {{name}}។', 'home.requests': 'សំណើវេន', 'home.signOut': 'ចាកចេញ', 'push.enable': 'បើកការជូនដំណឹង' },
  lo: { 'login.title': 'ຮ້ານຕັດຜົມຂອງທ່ານ ຢູ່ໃນມືທ່ານ.', 'login.email': 'ອີເມວ', 'login.password': 'ລະຫັດຜ່ານ', 'login.submit': 'ເຂົ້າລະບົບ', 'home.hello': 'ສະບາຍດີ {{name}}.', 'home.requests': 'ຄຳຮ້ອງຂໍຄິວ', 'home.signOut': 'ອອກຈາກລະບົບ', 'push.enable': 'ເປີດການແຈ້ງເຕືອນ' },
  mn: { 'login.title': 'Таны барбершоп таны гар дээр.', 'login.email': 'Имэйл', 'login.password': 'Нууц үг', 'login.submit': 'Нэвтрэх', 'home.hello': 'Сайн байна уу, {{name}}.', 'home.requests': 'Ээлжийн хүсэлтүүд', 'home.signOut': 'Гарах', 'push.enable': 'Мэдэгдэл идэвхжүүлэх' },
  kk: { 'login.title': 'Барбершопыңыз әрдайым қолыңызда.', 'login.email': 'Электрондық пошта', 'login.password': 'Құпиясөз', 'login.submit': 'Кіру', 'home.hello': 'Сәлем, {{name}}.', 'home.requests': 'Кезек сұраулары', 'home.signOut': 'Шығу', 'push.enable': 'Хабарландыруларды қосу' },
  uz: { 'login.title': 'Barbershopingiz doimo qo‘lingizda.', 'login.email': 'E-pochta', 'login.password': 'Parol', 'login.submit': 'Kirish', 'home.hello': 'Salom, {{name}}.', 'home.requests': 'Navbat so‘rovlari', 'home.signOut': 'Chiqish', 'push.enable': 'Bildirishnomalarni yoqish' },
  ky: { 'login.title': 'Барбершопуңуз ар дайым колуңузда.', 'login.email': 'Электрондук почта', 'login.password': 'Сырсөз', 'login.submit': 'Кирүү', 'home.hello': 'Салам, {{name}}.', 'home.requests': 'Кезек сурамдары', 'home.signOut': 'Чыгуу', 'push.enable': 'Эскертмелерди күйгүзүү' },
  tg: { 'login.title': 'Сартарошхонаи шумо ҳамеша дар дастатон.', 'login.email': 'Почтаи электронӣ', 'login.password': 'Рамз', 'login.submit': 'Ворид шудан', 'home.hello': 'Салом, {{name}}.', 'home.requests': 'Дархостҳои навбат', 'home.signOut': 'Баромадан', 'push.enable': 'Огоҳиномаҳоро фаъол кунед' },
};
