import type { Dictionary } from './types';

export const coreLegacy: Record<'de' | 'it' | 'nl' | 'ht', Dictionary> = {
  de: {
    'login.title': 'Dein Barbershop, direkt in deiner Tasche.', 'login.subtitle': 'Zugang für Owner, Administrator, Receptionist und Barber.', 'login.email': 'E-Mail', 'login.password': 'Passwort', 'login.invalidCredentials': 'E-Mail oder Passwort ist falsch.', 'login.failed': 'Anmeldung nicht möglich.', 'login.submitting': 'Anmeldung läuft…', 'login.submit': 'Anmelden', 'login.customerHint': 'Kunden können über den Link ihres Barbershops einen Platz anfragen, ohne ein Konto zu erstellen.',
    'home.hello': 'Hallo, {{name}}.', 'home.team': 'Team', 'home.body': 'BarberTrix hält das Team über neue Anfragen auf dem Laufenden, auch wenn die App im Hintergrund läuft.', 'home.requests': 'Warteschlangen-Anfragen', 'home.requestsText': 'Verwalte offene Anfragen und erhalte Änderungen in Echtzeit.', 'home.pushTitle': 'Keine neue Anfrage verpassen', 'home.pushBody': 'Aktiviere Systembenachrichtigungen, um rechtzeitig zu reagieren. Sichtbare Inhalte enthalten keine persönlichen Kundendaten.', 'home.signOut': 'Abmelden', 'push.enabledTitle': 'Benachrichtigungen aktiviert', 'push.enabledBody': 'Dieses Gerät erhält wichtige Aktualisierungen.', 'push.enabling': 'Wird aktiviert…', 'push.enable': 'Benachrichtigungen aktivieren',
  },
  it: {
    'login.title': 'Il tuo barbershop, anche in tasca.', 'login.subtitle': 'Accesso per i ruoli Owner, Administrator, Receptionist e Barber.', 'login.email': 'E-mail', 'login.password': 'Password', 'login.invalidCredentials': 'E-mail o password non corretti.', 'login.failed': 'Impossibile accedere.', 'login.submitting': 'Accesso…', 'login.submit': 'Accedi', 'login.customerHint': 'I clienti possono richiedere un turno senza creare un account tramite il link del barbershop.',
    'home.hello': 'Ciao, {{name}}.', 'home.team': 'team', 'home.body': 'BarberTrix mantiene il team aggiornato sulle nuove richieste anche quando l’app è in background.', 'home.requests': 'Richieste di turno', 'home.requestsText': 'Gestisci le richieste in attesa e ricevi aggiornamenti in tempo reale.', 'home.pushTitle': 'Non perdere nuove richieste', 'home.pushBody': 'Attiva le notifiche di sistema per rispondere in tempo. Il contenuto visibile non include dati personali del cliente.', 'home.signOut': 'Esci', 'push.enabledTitle': 'Notifiche attivate', 'push.enabledBody': 'Questo dispositivo riceverà aggiornamenti importanti.', 'push.enabling': 'Attivazione…', 'push.enable': 'Attiva notifiche',
  },
  nl: {
    'login.title': 'Je barbershop, ook in je broekzak.', 'login.subtitle': 'Toegang voor Owner, Administrator, Receptionist en Barber.', 'login.email': 'E-mail', 'login.password': 'Wachtwoord', 'login.invalidCredentials': 'Onjuist e-mailadres of wachtwoord.', 'login.failed': 'Inloggen is niet gelukt.', 'login.submitting': 'Bezig met inloggen…', 'login.submit': 'Inloggen', 'login.customerHint': 'Klanten kunnen via de link van hun barbershop een beurt aanvragen zonder een account te maken.',
    'home.hello': 'Hallo, {{name}}.', 'home.team': 'team', 'home.body': 'BarberTrix houdt het team op de hoogte van nieuwe aanvragen, ook wanneer de app op de achtergrond draait.', 'home.requests': 'Beurtaanvragen', 'home.requestsText': 'Beheer openstaande aanvragen en ontvang realtime updates.', 'home.pushTitle': 'Mis geen nieuwe aanvraag', 'home.pushBody': 'Schakel systeemmeldingen in om op tijd te reageren. Zichtbare meldingen bevatten geen persoonlijke klantgegevens.', 'home.signOut': 'Uitloggen', 'push.enabledTitle': 'Meldingen ingeschakeld', 'push.enabledBody': 'Dit apparaat ontvangt belangrijke updates.', 'push.enabling': 'Inschakelen…', 'push.enable': 'Meldingen inschakelen',
  },
  ht: {
    'login.title': 'Babèshop ou, menm nan pòch ou.', 'login.subtitle': 'Aksè pou Owner, Administrator, Receptionist ak Barber.', 'login.email': 'Imèl', 'login.password': 'Modpas', 'login.invalidCredentials': 'Imèl oswa modpas pa kòrèk.', 'login.failed': 'Nou pa t kapab konekte w.', 'login.submitting': 'Ap konekte…', 'login.submit': 'Konekte', 'login.customerHint': 'Kliyan yo ka mande yon plas san kreye kont atravè lyen babèshop la.',
    'home.hello': 'Bonjou, {{name}}.', 'home.team': 'ekip', 'home.body': 'BarberTrix kenbe ekip la enfòme sou nouvo demann menm lè aplikasyon an ap travay an aryè-plan.', 'home.requests': 'Demann pou plas', 'home.requestsText': 'Jere demann annatant epi resevwa chanjman an tan reyèl.', 'home.pushTitle': 'Pa rate nouvo demann', 'home.pushBody': 'Aktive notifikasyon sistèm pou reponn alè. Kontni vizib la pa gen done pèsonèl kliyan.', 'home.signOut': 'Dekonekte', 'push.enabledTitle': 'Notifikasyon aktive', 'push.enabledBody': 'Aparèy sa a ap resevwa mizajou enpòtan.', 'push.enabling': 'Ap aktive…', 'push.enable': 'Aktive notifikasyon',
  },
};
