import type { Dictionary } from './types';

export const europeWave1Mobile: Record<string, Dictionary> = {
  pl: {
    'login.title': 'Twój barbershop, także w kieszeni.', 'login.subtitle': 'Dostęp dla ról Owner, Administrator, Receptionist i Barber.', 'login.email': 'E-mail', 'login.password': 'Hasło', 'login.invalidCredentials': 'Nieprawidłowy e-mail lub hasło.', 'login.failed': 'Nie udało się zalogować.', 'login.submitting': 'Logowanie…', 'login.submit': 'Zaloguj się', 'login.customerHint': 'Klienci mogą poprosić o miejsce bez zakładania konta przez link barbershopu.',
    'home.hello': 'Cześć, {{name}}.', 'home.team': 'zespół', 'home.body': 'M3 informuje zespół o nowych zgłoszeniach nawet wtedy, gdy BarberTrix działa w tle.', 'home.requests': 'Prośby o miejsce', 'home.requestsText': 'Zarządzaj oczekującymi zgłoszeniami i otrzymuj aktualizacje w czasie rzeczywistym.', 'home.pushTitle': 'Nie przegap nowych zgłoszeń', 'home.pushBody': 'Włącz powiadomienia systemowe, aby reagować na czas. Widoczna treść nie zawiera danych osobowych klienta.', 'home.signOut': 'Wyloguj się', 'push.enabledTitle': 'Powiadomienia włączone', 'push.enabledBody': 'To urządzenie będzie otrzymywać ważne aktualizacje.', 'push.enabling': 'Włączanie…', 'push.enable': 'Włącz powiadomienia',
  },
  ro: {
    'login.title': 'Frizeria ta, chiar în buzunar.', 'login.subtitle': 'Acces pentru rolurile Owner, Administrator, Receptionist și Barber.', 'login.email': 'E-mail', 'login.password': 'Parolă', 'login.invalidCredentials': 'E-mail sau parolă incorectă.', 'login.failed': 'Nu am putut să te autentificăm.', 'login.submitting': 'Se autentifică…', 'login.submit': 'Autentificare', 'login.customerHint': 'Clienții pot solicita un loc fără cont prin linkul frizeriei.',
    'home.hello': 'Salut, {{name}}.', 'home.team': 'echipă', 'home.body': 'M3 ține echipa la curent cu solicitările noi chiar și când BarberTrix rulează în fundal.', 'home.requests': 'Solicitări de loc', 'home.requestsText': 'Gestionează solicitările în așteptare și primește actualizări în timp real.', 'home.pushTitle': 'Nu rata solicitările noi', 'home.pushBody': 'Activează notificările sistemului pentru a răspunde la timp. Conținutul vizibil nu include date personale ale clientului.', 'home.signOut': 'Deconectare', 'push.enabledTitle': 'Notificări activate', 'push.enabledBody': 'Acest dispozitiv va primi actualizări importante.', 'push.enabling': 'Se activează…', 'push.enable': 'Activează notificările',
  },
  sv: {
    'login.title': 'Din barbershop, direkt i fickan.', 'login.subtitle': 'Åtkomst för rollerna Owner, Administrator, Receptionist och Barber.', 'login.email': 'E-post', 'login.password': 'Lösenord', 'login.invalidCredentials': 'Fel e-post eller lösenord.', 'login.failed': 'Det gick inte att logga in.', 'login.submitting': 'Loggar in…', 'login.submit': 'Logga in', 'login.customerHint': 'Kunder kan begära en plats utan konto via barbershopens länk.',
    'home.hello': 'Hej, {{name}}.', 'home.team': 'team', 'home.body': 'M3 håller teamet informerat om nya förfrågningar även när BarberTrix körs i bakgrunden.', 'home.requests': 'Platsförfrågningar', 'home.requestsText': 'Hantera väntande förfrågningar och få uppdateringar i realtid.', 'home.pushTitle': 'Missa inga nya förfrågningar', 'home.pushBody': 'Aktivera systemaviseringar för att svara i tid. Synligt innehåll innehåller inga personuppgifter om kunden.', 'home.signOut': 'Logga ut', 'push.enabledTitle': 'Aviseringar aktiverade', 'push.enabledBody': 'Den här enheten får viktiga uppdateringar.', 'push.enabling': 'Aktiverar…', 'push.enable': 'Aktivera aviseringar',
  },
  da: {
    'login.title': 'Din barbershop, lige i lommen.', 'login.subtitle': 'Adgang for rollerne Owner, Administrator, Receptionist og Barber.', 'login.email': 'E-mail', 'login.password': 'Adgangskode', 'login.invalidCredentials': 'Forkert e-mail eller adgangskode.', 'login.failed': 'Vi kunne ikke logge dig ind.', 'login.submitting': 'Logger ind…', 'login.submit': 'Log ind', 'login.customerHint': 'Kunder kan anmode om en plads uden konto via barbershoppens link.',
    'home.hello': 'Hej, {{name}}.', 'home.team': 'team', 'home.body': 'M3 holder teamet informeret om nye anmodninger, også når BarberTrix kører i baggrunden.', 'home.requests': 'Pladsanmodninger', 'home.requestsText': 'Administrer ventende anmodninger og modtag opdateringer i realtid.', 'home.pushTitle': 'Gå ikke glip af nye anmodninger', 'home.pushBody': 'Aktivér systemnotifikationer for at svare i tide. Synligt indhold indeholder ikke kundens personoplysninger.', 'home.signOut': 'Log ud', 'push.enabledTitle': 'Notifikationer aktiveret', 'push.enabledBody': 'Denne enhed modtager vigtige opdateringer.', 'push.enabling': 'Aktiverer…', 'push.enable': 'Aktivér notifikationer',
  },
  nb: {
    'login.title': 'Barbershopen din, rett i lomma.', 'login.subtitle': 'Tilgang for rollene Owner, Administrator, Receptionist og Barber.', 'login.email': 'E-post', 'login.password': 'Passord', 'login.invalidCredentials': 'Feil e-post eller passord.', 'login.failed': 'Vi kunne ikke logge deg inn.', 'login.submitting': 'Logger inn…', 'login.submit': 'Logg inn', 'login.customerHint': 'Kunder kan be om en plass uten konto via lenken til barbershopen.',
    'home.hello': 'Hei, {{name}}.', 'home.team': 'team', 'home.body': 'M3 holder teamet informert om nye forespørsler selv når BarberTrix kjører i bakgrunnen.', 'home.requests': 'Plassforespørsler', 'home.requestsText': 'Administrer ventende forespørsler og motta oppdateringer i sanntid.', 'home.pushTitle': 'Ikke gå glipp av nye forespørsler', 'home.pushBody': 'Aktiver systemvarsler for å svare i tide. Synlig innhold inneholder ikke personopplysninger om kunden.', 'home.signOut': 'Logg ut', 'push.enabledTitle': 'Varsler aktivert', 'push.enabledBody': 'Denne enheten vil motta viktige oppdateringer.', 'push.enabling': 'Aktiverer…', 'push.enable': 'Aktiver varsler',
  },
  fi: {
    'login.title': 'Parturiliikkeesi, suoraan taskussasi.', 'login.subtitle': 'Pääsy rooleille Owner, Administrator, Receptionist ja Barber.', 'login.email': 'Sähköposti', 'login.password': 'Salasana', 'login.invalidCredentials': 'Virheellinen sähköposti tai salasana.', 'login.failed': 'Kirjautuminen epäonnistui.', 'login.submitting': 'Kirjaudutaan…', 'login.submit': 'Kirjaudu sisään', 'login.customerHint': 'Asiakkaat voivat pyytää vuoroa ilman tiliä parturiliikkeen linkin kautta.',
    'home.hello': 'Hei, {{name}}.', 'home.team': 'tiimi', 'home.body': 'M3 pitää tiimin ajan tasalla uusista pyynnöistä myös silloin, kun BarberTrix toimii taustalla.', 'home.requests': 'Vuoropyynnöt', 'home.requestsText': 'Hallitse odottavia pyyntöjä ja vastaanota reaaliaikaisia päivityksiä.', 'home.pushTitle': 'Älä missaa uusia pyyntöjä', 'home.pushBody': 'Ota järjestelmäilmoitukset käyttöön vastataksesi ajoissa. Näkyvä sisältö ei sisällä asiakkaan henkilötietoja.', 'home.signOut': 'Kirjaudu ulos', 'push.enabledTitle': 'Ilmoitukset käytössä', 'push.enabledBody': 'Tämä laite vastaanottaa tärkeitä päivityksiä.', 'push.enabling': 'Otetaan käyttöön…', 'push.enable': 'Ota ilmoitukset käyttöön',
  },
  cs: {
    'login.title': 'Vaše holičství, přímo v kapse.', 'login.subtitle': 'Přístup pro role Owner, Administrator, Receptionist a Barber.', 'login.email': 'E-mail', 'login.password': 'Heslo', 'login.invalidCredentials': 'Nesprávný e-mail nebo heslo.', 'login.failed': 'Přihlášení se nezdařilo.', 'login.submitting': 'Přihlašování…', 'login.submit': 'Přihlásit se', 'login.customerHint': 'Zákazníci mohou požádat o místo bez účtu prostřednictvím odkazu holičství.',
    'home.hello': 'Ahoj, {{name}}.', 'home.team': 'tým', 'home.body': 'M3 informuje tým o nových požadavcích, i když BarberTrix běží na pozadí.', 'home.requests': 'Požadavky na místo', 'home.requestsText': 'Spravujte čekající požadavky a dostávejte aktualizace v reálném čase.', 'home.pushTitle': 'Nezmeškejte nové požadavky', 'home.pushBody': 'Zapněte systémová oznámení, abyste mohli reagovat včas. Viditelný obsah neobsahuje osobní údaje zákazníka.', 'home.signOut': 'Odhlásit se', 'push.enabledTitle': 'Oznámení zapnuta', 'push.enabledBody': 'Toto zařízení bude dostávat důležité aktualizace.', 'push.enabling': 'Zapínání…', 'push.enable': 'Zapnout oznámení',
  },
  el: {
    'login.title': 'Το κουρείο σας, στην τσέπη σας.', 'login.subtitle': 'Πρόσβαση για τους ρόλους Owner, Administrator, Receptionist και Barber.', 'login.email': 'Email', 'login.password': 'Κωδικός πρόσβασης', 'login.invalidCredentials': 'Λάθος email ή κωδικός πρόσβασης.', 'login.failed': 'Δεν ήταν δυνατή η σύνδεση.', 'login.submitting': 'Σύνδεση…', 'login.submit': 'Σύνδεση', 'login.customerHint': 'Οι πελάτες μπορούν να ζητήσουν θέση χωρίς λογαριασμό μέσω του συνδέσμου του κουρείου.',
    'home.hello': 'Γεια, {{name}}.', 'home.team': 'ομάδα', 'home.body': 'Το M3 ενημερώνει την ομάδα για νέα αιτήματα ακόμη και όταν το BarberTrix λειτουργεί στο παρασκήνιο.', 'home.requests': 'Αιτήματα θέσης', 'home.requestsText': 'Διαχειριστείτε εκκρεμή αιτήματα και λάβετε ενημερώσεις σε πραγματικό χρόνο.', 'home.pushTitle': 'Μην χάσετε νέα αιτήματα', 'home.pushBody': 'Ενεργοποιήστε τις ειδοποιήσεις συστήματος για έγκαιρη απάντηση. Το ορατό περιεχόμενο δεν περιλαμβάνει προσωπικά δεδομένα πελάτη.', 'home.signOut': 'Αποσύνδεση', 'push.enabledTitle': 'Οι ειδοποιήσεις ενεργοποιήθηκαν', 'push.enabledBody': 'Αυτή η συσκευή θα λαμβάνει σημαντικές ενημερώσεις.', 'push.enabling': 'Ενεργοποίηση…', 'push.enable': 'Ενεργοποίηση ειδοποιήσεων',
  },
  tr: {
    'login.title': 'Berber dükkânınız, cebinizde.', 'login.subtitle': 'Owner, Administrator, Receptionist ve Barber rolleri için erişim.', 'login.email': 'E-posta', 'login.password': 'Şifre', 'login.invalidCredentials': 'E-posta veya şifre hatalı.', 'login.failed': 'Giriş yapılamadı.', 'login.submitting': 'Giriş yapılıyor…', 'login.submit': 'Giriş yap', 'login.customerHint': 'Müşteriler, berber dükkânı bağlantısı üzerinden hesap oluşturmadan sıra talep edebilir.',
    'home.hello': 'Merhaba, {{name}}.', 'home.team': 'ekip', 'home.body': 'M3, BarberTrix arka planda çalışırken bile ekibi yeni talepler hakkında bilgilendirir.', 'home.requests': 'Sıra talepleri', 'home.requestsText': 'Bekleyen talepleri yönetin ve gerçek zamanlı güncellemeler alın.', 'home.pushTitle': 'Yeni talepleri kaçırmayın', 'home.pushBody': 'Zamanında yanıt vermek için sistem bildirimlerini etkinleştirin. Görünür içerik müşteri kişisel verilerini içermez.', 'home.signOut': 'Çıkış yap', 'push.enabledTitle': 'Bildirimler etkin', 'push.enabledBody': 'Bu cihaz önemli güncellemeleri alacak.', 'push.enabling': 'Etkinleştiriliyor…', 'push.enable': 'Bildirimleri etkinleştir',
  },
  uk: {
    'login.title': 'Ваш барбершоп — у вашій кишені.', 'login.subtitle': 'Доступ для ролей Owner, Administrator, Receptionist і Barber.', 'login.email': 'Ел. пошта', 'login.password': 'Пароль', 'login.invalidCredentials': 'Неправильна електронна пошта або пароль.', 'login.failed': 'Не вдалося увійти.', 'login.submitting': 'Вхід…', 'login.submit': 'Увійти', 'login.customerHint': 'Клієнти можуть запросити місце без створення акаунта через посилання барбершопу.',
    'home.hello': 'Привіт, {{name}}.', 'home.team': 'команда', 'home.body': 'M3 інформує команду про нові запити навіть тоді, коли BarberTrix працює у фоновому режимі.', 'home.requests': 'Запити на місце', 'home.requestsText': 'Керуйте запитами, що очікують, і отримуйте оновлення в реальному часі.', 'home.pushTitle': 'Не пропускайте нові запити', 'home.pushBody': 'Увімкніть системні сповіщення, щоб відповідати вчасно. Видимий вміст не містить персональних даних клієнта.', 'home.signOut': 'Вийти', 'push.enabledTitle': 'Сповіщення увімкнено', 'push.enabledBody': 'Цей пристрій отримуватиме важливі оновлення.', 'push.enabling': 'Увімкнення…', 'push.enable': 'Увімкнути сповіщення',
  },
  ru: {
    'login.title': 'Ваш барбершоп — прямо в кармане.', 'login.subtitle': 'Доступ для ролей Owner, Administrator, Receptionist и Barber.', 'login.email': 'Эл. почта', 'login.password': 'Пароль', 'login.invalidCredentials': 'Неверная электронная почта или пароль.', 'login.failed': 'Не удалось войти.', 'login.submitting': 'Вход…', 'login.submit': 'Войти', 'login.customerHint': 'Клиенты могут запросить место без создания аккаунта по ссылке барбершопа.',
    'home.hello': 'Привет, {{name}}.', 'home.team': 'команда', 'home.body': 'M3 информирует команду о новых запросах, даже когда BarberTrix работает в фоновом режиме.', 'home.requests': 'Запросы на место', 'home.requestsText': 'Управляйте ожидающими запросами и получайте обновления в реальном времени.', 'home.pushTitle': 'Не пропускайте новые запросы', 'home.pushBody': 'Включите системные уведомления, чтобы отвечать вовремя. Видимое содержимое не включает персональные данные клиента.', 'home.signOut': 'Выйти', 'push.enabledTitle': 'Уведомления включены', 'push.enabledBody': 'Это устройство будет получать важные обновления.', 'push.enabling': 'Включение…', 'push.enable': 'Включить уведомления',
  },
};
