<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../BarberTrix.Application/BarberTrix.Application.csproj" />
    <ProjectReference Include="../BarberTrix.Domain/BarberTrix.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.*" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="BarberTrix.Api.Tests" />
  </ItemGroup>
</Project>
