import type { Dictionary } from './types'

type AfricaLocale = 'ar' | 'sw' | 'af' | 'am' | 'so' | 'ha' | 'yo' | 'ig' | 'zu' | 'xh'

const core = (values: Dictionary): Dictionary => values

export const africaWave1: Record<AfricaLocale, Dictionary> = {
  ar: core({
    'language.label': 'اللغة', 'common.login': 'تسجيل الدخول', 'common.register': 'إنشاء حساب', 'common.email': 'البريد الإلكتروني', 'common.password': 'كلمة المرور', 'common.loading': 'جارٍ التحميل…',
    'home.nav.home': 'الرئيسية', 'home.nav.features': 'الميزات', 'home.nav.pricing': 'الأسعار', 'home.nav.contact': 'اتصل بنا', 'home.startFree': 'ابدأ مجانًا', 'home.hero.title1': 'نظّم صالون الحلاقة الخاص بك.', 'home.hero.title2': 'قدّم خدمة أفضل للعملاء.', 'home.viewFeatures': 'عرض الميزات',
    'login.welcome': 'مرحبًا بعودتك', 'login.subtitle': 'سجّل الدخول للمتابعة', 'login.submit': 'تسجيل الدخول', 'login.submitting': 'جارٍ تسجيل الدخول…', 'login.invalid': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.', 'login.genericError': 'تعذر تسجيل الدخول.',
    dashboard: 'لوحة التحكم', queueLive: 'قائمة الانتظار المباشرة', barbers: 'الحلاقون', services: 'الخدمات', appointments: 'المواعيد', customers: 'العملاء', payments: 'المدفوعات', reports: 'التقارير', team: 'الفريق', locations: 'الفروع', billing: 'الاشتراك', logout: 'تسجيل الخروج', refresh: 'تحديث', waiting: 'قيد الانتظار', completed: 'مكتمل', cancel: 'إلغاء', complete: 'إكمال'
  }),
  sw: core({ 'language.label':'Lugha','common.login':'Ingia','common.register':'Fungua akaunti','common.email':'Barua pepe','common.password':'Nenosiri','home.nav.home':'Nyumbani','home.nav.features':'Vipengele','home.nav.pricing':'Bei','home.nav.contact':'Mawasiliano','home.startFree':'Anza bila malipo','login.welcome':'Karibu tena','login.subtitle':'Ingia ili kuendelea','login.submit':'Ingia','login.submitting':'Inaingia…','login.invalid':'Barua pepe au nenosiri si sahihi.','dashboard':'Dashibodi','queueLive':'Foleni ya moja kwa moja','barbers':'Vinyozi','services':'Huduma','appointments':'Miadi','customers':'Wateja','payments':'Malipo','reports':'Ripoti','team':'Timu','locations':'Maeneo','billing':'Usajili','logout':'Toka','refresh':'Onyesha upya','waiting':'Inasubiri','completed':'Imekamilika','cancel':'Ghairi','complete':'Kamilisha' }),
  af: core({ 'language.label':'Taal','common.login':'Meld aan','common.register':'Skep rekening','common.email':'E-pos','common.password':'Wagwoord','home.nav.home':'Tuis','home.nav.features':'Kenmerke','home.nav.pricing':'Pryse','home.nav.contact':'Kontak','home.startFree':'Begin gratis','login.welcome':'Welkom terug','login.subtitle':'Meld aan om voort te gaan','login.submit':'Meld aan','login.submitting':'Besig om aan te meld…','login.invalid':'Verkeerde e-pos of wagwoord.','dashboard':'Kontroleskerm','queueLive':'Regstreekse ry','barbers':'Barbiers','services':'Dienste','appointments':'Afsprake','customers':'Kliënte','payments':'Betalings','reports':'Verslae','team':'Span','locations':'Liggings','billing':'Intekening','logout':'Meld af','refresh':'Verfris','waiting':'Wag','completed':'Voltooi','cancel':'Kanselleer','complete':'Voltooi' }),
  am: core({ 'language.label':'ቋንቋ','common.login':'ግባ','common.register':'መለያ ፍጠር','common.email':'ኢሜይል','common.password':'የይለፍ ቃል','home.nav.home':'መነሻ','home.nav.features':'ባህሪያት','home.nav.pricing':'ዋጋ','home.nav.contact':'እውቂያ','login.welcome':'እንኳን ደህና መጡ','login.subtitle':'ለመቀጠል ይግቡ','login.submit':'ግባ','dashboard':'ዳሽቦርድ','barbers':'ፀጉር አስተካካዮች','services':'አገልግሎቶች','appointments':'ቀጠሮዎች','customers':'ደንበኞች','payments':'ክፍያዎች','reports':'ሪፖርቶች','team':'ቡድን','locations':'ቦታዎች','logout':'ውጣ','refresh':'አድስ','waiting':'በመጠበቅ ላይ','completed':'ተጠናቋል','cancel':'ሰርዝ' }),
  so: core({ 'language.label':'Luqad','common.login':'Gal','common.register':'Akoon samee','common.email':'Iimayl','common.password':'Furaha sirta','home.nav.home':'Bogga hore','home.nav.features':'Astaamaha','home.nav.pricing':'Qiimaha','home.nav.contact':'Xiriir','login.welcome':'Soo dhawoow mar kale','login.subtitle':'Gal si aad u sii waddo','login.submit':'Gal','dashboard':'Dashboard','queueLive':'Saf toos ah','barbers':'Timo-jarayaal','services':'Adeegyada','appointments':'Ballamaha','customers':'Macaamiisha','payments':'Lacag-bixinnada','reports':'Warbixinno','team':'Kooxda','locations':'Goobaha','logout':'Ka bax','refresh':'Cusboonaysii','waiting':'Sugaya','completed':'La dhammeeyay','cancel':'Jooji','complete':'Dhammaystir' }),
  ha: core({ 'language.label':'Harshe','common.login':'Shiga','common.register':'Ƙirƙiri asusu','common.email':'Imel','common.password':'Kalmar sirri','home.nav.home':'Gida','home.nav.features':'Fasali','home.nav.pricing':'Farashi','home.nav.contact':'Tuntuɓa','login.welcome':'Barka da dawowa','login.subtitle':'Shiga don ci gaba','login.submit':'Shiga','dashboard':'Dashboard','queueLive':'Jerin jira kai tsaye','barbers':'Masu aski','services':'Ayyuka','appointments':'Alƙawura','customers':'Abokan ciniki','payments':'Biya','reports':'Rahotanni','team':'Ƙungiya','locations':'Wurare','logout':'Fita','refresh':'Sabunta','waiting':'Ana jira','completed':'An kammala','cancel':'Soke','complete':'Kammala' }),
  yo: core({ 'language.label':'Èdè','common.login':'Wọlé','common.register':'Ṣẹda àkọọlẹ','common.email':'Ímeèlì','common.password':'Ọ̀rọ̀ aṣínà','home.nav.home':'Ilé','home.nav.features':'Àwọn ẹya','home.nav.pricing':'Iye','home.nav.contact':'Kan si wa','login.welcome':'Káàbọ̀ padà','login.subtitle':'Wọlé láti tẹ̀síwájú','login.submit':'Wọlé','dashboard':'Dasibodu','queueLive':'Ìlà ìdúró laaye','barbers':'Àwọn onírun','services':'Àwọn iṣẹ́','appointments':'Àwọn ìpàdé','customers':'Àwọn oníbàárà','payments':'Àwọn ìsanwó','reports':'Àwọn ìròyìn','team':'Ẹgbẹ́','locations':'Àwọn ibi','logout':'Jáde','refresh':'Túnṣe','waiting':'Ń dúró','completed':'Ti pari','cancel':'Fagilé','complete':'Pari' }),
  ig: core({ 'language.label':'Asụsụ','common.login':'Banye','common.register':'Mepụta akaụntụ','common.email':'Email','common.password':'Okwuntughe','home.nav.home':'Ụlọ','home.nav.features':'Njirimara','home.nav.pricing':'Ọnụahịa','home.nav.contact':'Kpọtụrụ','login.welcome':'Nnọọ ọzọ','login.subtitle':'Banye ka ị gaa n’ihu','login.submit':'Banye','dashboard':'Dashboard','queueLive':'Ahịrị ndụ','barbers':'Ndị na-akpụ isi','services':'Ọrụ','appointments':'Oge nzukọ','customers':'Ndị ahịa','payments':'Ịkwụ ụgwọ','reports':'Akụkọ','team':'Otu','locations':'Ebe','logout':'Pụọ','refresh':'Mee ọhụrụ','waiting':'Na-eche','completed':'Emechara','cancel':'Kagbuo','complete':'Mechaa' }),
  zu: core({ 'language.label':'Ulimi','common.login':'Ngena','common.register':'Dala i-akhawunti','common.email':'I-imeyili','common.password':'Iphasiwedi','home.nav.home':'Ikhaya','home.nav.features':'Izici','home.nav.pricing':'Amanani','home.nav.contact':'Xhumana','login.welcome':'Siyakwamukela futhi','login.subtitle':'Ngena ukuze uqhubeke','login.submit':'Ngena','dashboard':'Ideshibhodi','queueLive':'Ulayini obukhoma','barbers':'Abagundi','services':'Izinsiza','appointments':'Ama-aphoyintimenti','customers':'Amakhasimende','payments':'Izinkokhelo','reports':'Imibiko','team':'Ithimba','locations':'Izindawo','logout':'Phuma','refresh':'Vuselela','waiting':'Kulindile','completed':'Kuqediwe','cancel':'Khansela','complete':'Qedela' }),
  xh: core({ 'language.label':'Ulwimi','common.login':'Ngena','common.register':'Yenza iakhawunti','common.email':'I-imeyile','common.password':'Igama lokugqitha','home.nav.home':'Ekhaya','home.nav.features':'Iimpawu','home.nav.pricing':'Amaxabiso','home.nav.contact':'Qhagamshelana','login.welcome':'Wamkelekile kwakhona','login.subtitle':'Ngena ukuze uqhubeke','login.submit':'Ngena','dashboard':'Ideshibhodi','queueLive':'Umgca ophilayo','barbers':'Abachebi','services':'Iinkonzo','appointments':'Izithuba','customers':'Abathengi','payments':'Iintlawulo','reports':'Iingxelo','team':'Iqela','locations':'Iindawo','logout':'Phuma','refresh':'Hlaziya','waiting':'Ilindile','completed':'Igqityiwe','cancel':'Rhoxisa','complete':'Gqiba' }),
}
