import type { Dictionary } from './types'
import type { OfficialLocale } from './officialLocales'

const es: Dictionary = {
  'appointmentsAdmin.eyebrow': 'AGENDA HÍBRIDA', 'appointmentsAdmin.title': 'Agenda de citas', 'appointmentsAdmin.lead': 'Organiza la semana, filtra por barbero y mueve reservas sin salir del panel.', 'appointmentsAdmin.customerPortal': 'Portal del cliente',
  'appointmentsAdmin.lockedTitle': 'Citas y agenda híbrida', 'appointmentsAdmin.lockedText': 'Reserva horarios, combina citas con turnos por llegada y gestiona la agenda del equipo.', 'appointmentsAdmin.controls': 'Controles de agenda', 'appointmentsAdmin.view': 'Vista de agenda', 'appointmentsAdmin.today': 'Hoy', 'appointmentsAdmin.week': 'Semana', 'appointmentsAdmin.date': 'Fecha', 'appointmentsAdmin.barber': 'Barbero', 'appointmentsAdmin.status': 'Estado', 'appointmentsAdmin.active': 'Activas',
  'appointmentsAdmin.status.Confirmed': 'Confirmada', 'appointmentsAdmin.status.CheckedIn': 'En espera', 'appointmentsAdmin.status.Completed': 'Completada', 'appointmentsAdmin.status.Cancelled': 'Cancelada', 'appointmentsAdmin.status.NoShow': 'No llegó',
  'appointmentsAdmin.daySummary': 'citas en el día seleccionado', 'appointmentsAdmin.weekSummary': 'citas en la semana seleccionada', 'appointmentsAdmin.noContact': 'Sin contacto registrado', 'appointmentsAdmin.reschedule': 'Reprogramar', 'appointmentsAdmin.checkIn': 'Check-in', 'appointmentsAdmin.cancel': 'Cancelar', 'appointmentsAdmin.complete': 'Completar',
  'appointmentsAdmin.emptyTitle': 'Agenda despejada', 'appointmentsAdmin.emptyText': 'No hay citas que coincidan con esta vista y filtros.', 'appointmentsAdmin.newEyebrow': 'NUEVA RESERVA', 'appointmentsAdmin.createTitle': 'Crear cita', 'appointmentsAdmin.customerName': 'Nombre del cliente', 'appointmentsAdmin.phone': 'Teléfono', 'appointmentsAdmin.email': 'Correo', 'appointmentsAdmin.service': 'Servicio', 'appointmentsAdmin.slotAvailable': 'Horario disponible', 'appointmentsAdmin.noSlots': 'Sin horarios disponibles', 'appointmentsAdmin.create': 'Crear cita',
  'appointmentsAdmin.qrAlt': 'Código QR del portal de clientes', 'appointmentsAdmin.selfService': 'Autoservicio del cliente', 'appointmentsAdmin.selfServiceText': 'Comparte el QR para que tus clientes reserven o tomen turno sin intervención del personal.', 'appointmentsAdmin.downloadQr': 'Descargar QR', 'appointmentsAdmin.rescheduleEyebrow': 'REPROGRAMAR', 'appointmentsAdmin.currently': 'actualmente {{date}}', 'appointmentsAdmin.newSlot': 'Nuevo horario', 'appointmentsAdmin.saveChange': 'Guardar cambio',
  'appointmentsAdmin.updated': 'Cita actualizada', 'appointmentsAdmin.updateError': 'No se pudo actualizar la cita', 'appointmentsAdmin.created': 'Cita creada', 'appointmentsAdmin.createError': 'No se pudo crear la cita', 'appointmentsAdmin.rescheduled': 'Cita reprogramada', 'appointmentsAdmin.rescheduleError': 'No se pudo reprogramar la cita',
}

const en: Dictionary = {
  'appointmentsAdmin.eyebrow': 'HYBRID SCHEDULE', 'appointmentsAdmin.title': 'Appointment schedule', 'appointmentsAdmin.lead': 'Organize the week, filter by barber, and move bookings without leaving the dashboard.', 'appointmentsAdmin.customerPortal': 'Customer portal', 'appointmentsAdmin.lockedTitle': 'Appointments and hybrid schedule', 'appointmentsAdmin.lockedText': 'Book time slots, combine appointments with walk-ins, and manage the team schedule.', 'appointmentsAdmin.controls': 'Schedule controls', 'appointmentsAdmin.view': 'Schedule view', 'appointmentsAdmin.today': 'Today', 'appointmentsAdmin.week': 'Week', 'appointmentsAdmin.date': 'Date', 'appointmentsAdmin.barber': 'Barber', 'appointmentsAdmin.status': 'Status', 'appointmentsAdmin.active': 'Active',
  'appointmentsAdmin.status.Confirmed': 'Confirmed', 'appointmentsAdmin.status.CheckedIn': 'Checked in', 'appointmentsAdmin.status.Completed': 'Completed', 'appointmentsAdmin.status.Cancelled': 'Cancelled', 'appointmentsAdmin.status.NoShow': 'No-show', 'appointmentsAdmin.daySummary': 'appointments on the selected day', 'appointmentsAdmin.weekSummary': 'appointments in the selected week', 'appointmentsAdmin.noContact': 'No contact information', 'appointmentsAdmin.reschedule': 'Reschedule', 'appointmentsAdmin.checkIn': 'Check in', 'appointmentsAdmin.cancel': 'Cancel', 'appointmentsAdmin.complete': 'Complete', 'appointmentsAdmin.emptyTitle': 'Schedule clear', 'appointmentsAdmin.emptyText': 'No appointments match this view and filters.', 'appointmentsAdmin.newEyebrow': 'NEW BOOKING', 'appointmentsAdmin.createTitle': 'Create appointment', 'appointmentsAdmin.customerName': 'Customer name', 'appointmentsAdmin.phone': 'Phone', 'appointmentsAdmin.email': 'Email', 'appointmentsAdmin.service': 'Service', 'appointmentsAdmin.slotAvailable': 'Available time', 'appointmentsAdmin.noSlots': 'No times available', 'appointmentsAdmin.create': 'Create appointment', 'appointmentsAdmin.qrAlt': 'Customer portal QR code', 'appointmentsAdmin.selfService': 'Customer self-service', 'appointmentsAdmin.selfServiceText': 'Share the QR so customers can book or join the queue without staff assistance.', 'appointmentsAdmin.downloadQr': 'Download QR', 'appointmentsAdmin.rescheduleEyebrow': 'RESCHEDULE', 'appointmentsAdmin.currently': 'currently {{date}}', 'appointmentsAdmin.newSlot': 'New time', 'appointmentsAdmin.saveChange': 'Save change', 'appointmentsAdmin.updated': 'Appointment updated', 'appointmentsAdmin.updateError': 'Could not update the appointment', 'appointmentsAdmin.created': 'Appointment created', 'appointmentsAdmin.createError': 'Could not create the appointment', 'appointmentsAdmin.rescheduled': 'Appointment rescheduled', 'appointmentsAdmin.rescheduleError': 'Could not reschedule the appointment',
}

const pt: Dictionary = {
  'appointmentsAdmin.eyebrow': 'AGENDA HÍBRIDA', 'appointmentsAdmin.title': 'Agenda de agendamentos', 'appointmentsAdmin.lead': 'Organize a semana, filtre por barbeiro e mova reservas sem sair do painel.', 'appointmentsAdmin.customerPortal': 'Portal do cliente', 'appointmentsAdmin.lockedTitle': 'Agendamentos e agenda híbrida', 'appointmentsAdmin.lockedText': 'Reserve horários, combine agendamentos com atendimentos por chegada e gerencie a agenda da equipe.', 'appointmentsAdmin.controls': 'Controles da agenda', 'appointmentsAdmin.view': 'Visualização da agenda', 'appointmentsAdmin.today': 'Hoje', 'appointmentsAdmin.week': 'Semana', 'appointmentsAdmin.date': 'Data', 'appointmentsAdmin.barber': 'Barbeiro', 'appointmentsAdmin.status': 'Status', 'appointmentsAdmin.active': 'Ativos',
  'appointmentsAdmin.status.Confirmed': 'Confirmado', 'appointmentsAdmin.status.CheckedIn': 'Em espera', 'appointmentsAdmin.status.Completed': 'Concluído', 'appointmentsAdmin.status.Cancelled': 'Cancelado', 'appointmentsAdmin.status.NoShow': 'Não compareceu', 'appointmentsAdmin.daySummary': 'agendamentos no dia selecionado', 'appointmentsAdmin.weekSummary': 'agendamentos na semana selecionada', 'appointmentsAdmin.noContact': 'Sem contato cadastrado', 'appointmentsAdmin.reschedule': 'Reagendar', 'appointmentsAdmin.checkIn': 'Check-in', 'appointmentsAdmin.cancel': 'Cancelar', 'appointmentsAdmin.complete': 'Concluir', 'appointmentsAdmin.emptyTitle': 'Agenda livre', 'appointmentsAdmin.emptyText': 'Nenhum agendamento corresponde a esta visualização e aos filtros.', 'appointmentsAdmin.newEyebrow': 'NOVA RESERVA', 'appointmentsAdmin.createTitle': 'Criar agendamento', 'appointmentsAdmin.customerName': 'Nome do cliente', 'appointmentsAdmin.phone': 'Telefone', 'appointmentsAdmin.email': 'E-mail', 'appointmentsAdmin.service': 'Serviço', 'appointmentsAdmin.slotAvailable': 'Horário disponível', 'appointmentsAdmin.noSlots': 'Sem horários disponíveis', 'appointmentsAdmin.create': 'Criar agendamento', 'appointmentsAdmin.qrAlt': 'Código QR do portal de clientes', 'appointmentsAdmin.selfService': 'Autoatendimento do cliente', 'appointmentsAdmin.selfServiceText': 'Compartilhe o QR para que seus clientes agendem ou entrem na fila sem ajuda da equipe.', 'appointmentsAdmin.downloadQr': 'Baixar QR', 'appointmentsAdmin.rescheduleEyebrow': 'REAGENDAR', 'appointmentsAdmin.currently': 'atualmente {{date}}', 'appointmentsAdmin.newSlot': 'Novo horário', 'appointmentsAdmin.saveChange': 'Salvar alteração', 'appointmentsAdmin.updated': 'Agendamento atualizado', 'appointmentsAdmin.updateError': 'Não foi possível atualizar o agendamento', 'appointmentsAdmin.created': 'Agendamento criado', 'appointmentsAdmin.createError': 'Não foi possível criar o agendamento', 'appointmentsAdmin.rescheduled': 'Agendamento reagendado', 'appointmentsAdmin.rescheduleError': 'Não foi possível reagendar o agendamento',
}

const fr: Dictionary = {
  'appointmentsAdmin.eyebrow': 'AGENDA HYBRIDE', 'appointmentsAdmin.title': 'Agenda des rendez-vous', 'appointmentsAdmin.lead': 'Organisez la semaine, filtrez par barbier et déplacez les réservations sans quitter le tableau de bord.', 'appointmentsAdmin.customerPortal': 'Portail client', 'appointmentsAdmin.lockedTitle': 'Rendez-vous et agenda hybride', 'appointmentsAdmin.lockedText': 'Réservez des créneaux, combinez rendez-vous et arrivées sans réservation, et gérez l’agenda de l’équipe.', 'appointmentsAdmin.controls': 'Contrôles de l’agenda', 'appointmentsAdmin.view': 'Vue de l’agenda', 'appointmentsAdmin.today': 'Aujourd’hui', 'appointmentsAdmin.week': 'Semaine', 'appointmentsAdmin.date': 'Date', 'appointmentsAdmin.barber': 'Barbier', 'appointmentsAdmin.status': 'Statut', 'appointmentsAdmin.active': 'Actifs',
  'appointmentsAdmin.status.Confirmed': 'Confirmé', 'appointmentsAdmin.status.CheckedIn': 'En attente', 'appointmentsAdmin.status.Completed': 'Terminé', 'appointmentsAdmin.status.Cancelled': 'Annulé', 'appointmentsAdmin.status.NoShow': 'Absent', 'appointmentsAdmin.daySummary': 'rendez-vous le jour sélectionné', 'appointmentsAdmin.weekSummary': 'rendez-vous la semaine sélectionnée', 'appointmentsAdmin.noContact': 'Aucun contact enregistré', 'appointmentsAdmin.reschedule': 'Reprogrammer', 'appointmentsAdmin.checkIn': 'Enregistrer l’arrivée', 'appointmentsAdmin.cancel': 'Annuler', 'appointmentsAdmin.complete': 'Terminer', 'appointmentsAdmin.emptyTitle': 'Agenda dégagé', 'appointmentsAdmin.emptyText': 'Aucun rendez-vous ne correspond à cette vue et à ces filtres.', 'appointmentsAdmin.newEyebrow': 'NOUVELLE RÉSERVATION', 'appointmentsAdmin.createTitle': 'Créer un rendez-vous', 'appointmentsAdmin.customerName': 'Nom du client', 'appointmentsAdmin.phone': 'Téléphone', 'appointmentsAdmin.email': 'E-mail', 'appointmentsAdmin.service': 'Service', 'appointmentsAdmin.slotAvailable': 'Créneau disponible', 'appointmentsAdmin.noSlots': 'Aucun créneau disponible', 'appointmentsAdmin.create': 'Créer le rendez-vous', 'appointmentsAdmin.qrAlt': 'Code QR du portail client', 'appointmentsAdmin.selfService': 'Libre-service client', 'appointmentsAdmin.selfServiceText': 'Partagez le QR pour que vos clients réservent ou rejoignent la file sans intervention du personnel.', 'appointmentsAdmin.downloadQr': 'Télécharger le QR', 'appointmentsAdmin.rescheduleEyebrow': 'REPROGRAMMER', 'appointmentsAdmin.currently': 'actuellement {{date}}', 'appointmentsAdmin.newSlot': 'Nouveau créneau', 'appointmentsAdmin.saveChange': 'Enregistrer', 'appointmentsAdmin.updated': 'Rendez-vous mis à jour', 'appointmentsAdmin.updateError': 'Impossible de mettre à jour le rendez-vous', 'appointmentsAdmin.created': 'Rendez-vous créé', 'appointmentsAdmin.createError': 'Impossible de créer le rendez-vous', 'appointmentsAdmin.rescheduled': 'Rendez-vous reprogrammé', 'appointmentsAdmin.rescheduleError': 'Impossible de reprogrammer le rendez-vous',
}

const ht: Dictionary = {
  'appointmentsAdmin.eyebrow': 'ORÈ IBRID', 'appointmentsAdmin.title': 'Orè randevou', 'appointmentsAdmin.lead': 'Òganize semèn nan, filtre pa babè epi deplase rezèvasyon san kite panèl la.', 'appointmentsAdmin.customerPortal': 'Pòtay kliyan', 'appointmentsAdmin.lockedTitle': 'Randevou ak orè ibrid', 'appointmentsAdmin.lockedText': 'Rezève lè, melanje randevou ak kliyan ki rive san randevou, epi jere orè ekip la.', 'appointmentsAdmin.controls': 'Kontwòl orè', 'appointmentsAdmin.view': 'Vizyalizasyon orè', 'appointmentsAdmin.today': 'Jodi a', 'appointmentsAdmin.week': 'Semèn', 'appointmentsAdmin.date': 'Dat', 'appointmentsAdmin.barber': 'Babè', 'appointmentsAdmin.status': 'Estati', 'appointmentsAdmin.active': 'Aktif',
  'appointmentsAdmin.status.Confirmed': 'Konfime', 'appointmentsAdmin.status.CheckedIn': 'Ap tann', 'appointmentsAdmin.status.Completed': 'Fini', 'appointmentsAdmin.status.Cancelled': 'Anile', 'appointmentsAdmin.status.NoShow': 'Pa vini', 'appointmentsAdmin.daySummary': 'randevou nan jou chwazi a', 'appointmentsAdmin.weekSummary': 'randevou nan semèn chwazi a', 'appointmentsAdmin.noContact': 'Pa gen kontak anrejistre', 'appointmentsAdmin.reschedule': 'Chanje lè', 'appointmentsAdmin.checkIn': 'Anrejistre rive', 'appointmentsAdmin.cancel': 'Anile', 'appointmentsAdmin.complete': 'Fini', 'appointmentsAdmin.emptyTitle': 'Orè a lib', 'appointmentsAdmin.emptyText': 'Pa gen randevou ki koresponn ak vizyalizasyon ak filtè sa yo.', 'appointmentsAdmin.newEyebrow': 'NOUVO REZÈVASYON', 'appointmentsAdmin.createTitle': 'Kreye randevou', 'appointmentsAdmin.customerName': 'Non kliyan', 'appointmentsAdmin.phone': 'Telefòn', 'appointmentsAdmin.email': 'Imèl', 'appointmentsAdmin.service': 'Sèvis', 'appointmentsAdmin.slotAvailable': 'Lè disponib', 'appointmentsAdmin.noSlots': 'Pa gen lè disponib', 'appointmentsAdmin.create': 'Kreye randevou', 'appointmentsAdmin.qrAlt': 'Kòd QR pòtay kliyan', 'appointmentsAdmin.selfService': 'Sèvis endepandan kliyan', 'appointmentsAdmin.selfServiceText': 'Pataje QR la pou kliyan yo ka rezève oswa pran plas san entèvansyon pèsonèl la.', 'appointmentsAdmin.downloadQr': 'Telechaje QR', 'appointmentsAdmin.rescheduleEyebrow': 'CHANJE LÈ', 'appointmentsAdmin.currently': 'kounye a {{date}}', 'appointmentsAdmin.newSlot': 'Nouvo lè', 'appointmentsAdmin.saveChange': 'Sove chanjman', 'appointmentsAdmin.updated': 'Randevou mete ajou', 'appointmentsAdmin.updateError': 'Nou pa t kapab mete randevou a ajou', 'appointmentsAdmin.created': 'Randevou kreye', 'appointmentsAdmin.createError': 'Nou pa t kapab kreye randevou a', 'appointmentsAdmin.rescheduled': 'Lè randevou chanje', 'appointmentsAdmin.rescheduleError': 'Nou pa t kapab chanje lè randevou a',
}

const de: Dictionary = {
  'appointmentsAdmin.eyebrow': 'HYBRID-TERMINKALENDER', 'appointmentsAdmin.title': 'Terminkalender', 'appointmentsAdmin.lead': 'Organisiere die Woche, filtere nach Barbier und verschiebe Buchungen direkt im Dashboard.', 'appointmentsAdmin.customerPortal': 'Kundenportal', 'appointmentsAdmin.lockedTitle': 'Termine und Hybrid-Kalender', 'appointmentsAdmin.lockedText': 'Buche Zeiten, kombiniere Termine mit Laufkundschaft und verwalte den Teamkalender.', 'appointmentsAdmin.controls': 'Kalendersteuerung', 'appointmentsAdmin.view': 'Kalenderansicht', 'appointmentsAdmin.today': 'Heute', 'appointmentsAdmin.week': 'Woche', 'appointmentsAdmin.date': 'Datum', 'appointmentsAdmin.barber': 'Barbier', 'appointmentsAdmin.status': 'Status', 'appointmentsAdmin.active': 'Aktiv',
  'appointmentsAdmin.status.Confirmed': 'Bestätigt', 'appointmentsAdmin.status.CheckedIn': 'Eingecheckt', 'appointmentsAdmin.status.Completed': 'Abgeschlossen', 'appointmentsAdmin.status.Cancelled': 'Storniert', 'appointmentsAdmin.status.NoShow': 'Nicht erschienen', 'appointmentsAdmin.daySummary': 'Termine am ausgewählten Tag', 'appointmentsAdmin.weekSummary': 'Termine in der ausgewählten Woche', 'appointmentsAdmin.noContact': 'Keine Kontaktdaten', 'appointmentsAdmin.reschedule': 'Verschieben', 'appointmentsAdmin.checkIn': 'Einchecken', 'appointmentsAdmin.cancel': 'Stornieren', 'appointmentsAdmin.complete': 'Abschließen', 'appointmentsAdmin.emptyTitle': 'Kalender frei', 'appointmentsAdmin.emptyText': 'Keine Termine entsprechen dieser Ansicht und den Filtern.', 'appointmentsAdmin.newEyebrow': 'NEUE BUCHUNG', 'appointmentsAdmin.createTitle': 'Termin erstellen', 'appointmentsAdmin.customerName': 'Kundenname', 'appointmentsAdmin.phone': 'Telefon', 'appointmentsAdmin.email': 'E-Mail', 'appointmentsAdmin.service': 'Dienstleistung', 'appointmentsAdmin.slotAvailable': 'Verfügbare Zeit', 'appointmentsAdmin.noSlots': 'Keine Zeiten verfügbar', 'appointmentsAdmin.create': 'Termin erstellen', 'appointmentsAdmin.qrAlt': 'QR-Code des Kundenportals', 'appointmentsAdmin.selfService': 'Kunden-Self-Service', 'appointmentsAdmin.selfServiceText': 'Teile den QR-Code, damit Kunden selbst buchen oder sich anstellen können.', 'appointmentsAdmin.downloadQr': 'QR herunterladen', 'appointmentsAdmin.rescheduleEyebrow': 'VERSCHIEBEN', 'appointmentsAdmin.currently': 'derzeit {{date}}', 'appointmentsAdmin.newSlot': 'Neue Zeit', 'appointmentsAdmin.saveChange': 'Änderung speichern', 'appointmentsAdmin.updated': 'Termin aktualisiert', 'appointmentsAdmin.updateError': 'Termin konnte nicht aktualisiert werden', 'appointmentsAdmin.created': 'Termin erstellt', 'appointmentsAdmin.createError': 'Termin konnte nicht erstellt werden', 'appointmentsAdmin.rescheduled': 'Termin verschoben', 'appointmentsAdmin.rescheduleError': 'Termin konnte nicht verschoben werden',
}

const it: Dictionary = {
  'appointmentsAdmin.eyebrow': 'AGENDA IBRIDA', 'appointmentsAdmin.title': 'Agenda appuntamenti', 'appointmentsAdmin.lead': 'Organizza la settimana, filtra per barbiere e sposta le prenotazioni senza uscire dal pannello.', 'appointmentsAdmin.customerPortal': 'Portale cliente', 'appointmentsAdmin.lockedTitle': 'Appuntamenti e agenda ibrida', 'appointmentsAdmin.lockedText': 'Prenota orari, combina appuntamenti e clienti senza prenotazione e gestisci l’agenda del team.', 'appointmentsAdmin.controls': 'Controlli agenda', 'appointmentsAdmin.view': 'Vista agenda', 'appointmentsAdmin.today': 'Oggi', 'appointmentsAdmin.week': 'Settimana', 'appointmentsAdmin.date': 'Data', 'appointmentsAdmin.barber': 'Barbiere', 'appointmentsAdmin.status': 'Stato', 'appointmentsAdmin.active': 'Attivi',
  'appointmentsAdmin.status.Confirmed': 'Confermato', 'appointmentsAdmin.status.CheckedIn': 'In attesa', 'appointmentsAdmin.status.Completed': 'Completato', 'appointmentsAdmin.status.Cancelled': 'Annullato', 'appointmentsAdmin.status.NoShow': 'Non presentato', 'appointmentsAdmin.daySummary': 'appuntamenti nel giorno selezionato', 'appointmentsAdmin.weekSummary': 'appuntamenti nella settimana selezionata', 'appointmentsAdmin.noContact': 'Nessun contatto registrato', 'appointmentsAdmin.reschedule': 'Riprogramma', 'appointmentsAdmin.checkIn': 'Check-in', 'appointmentsAdmin.cancel': 'Annulla', 'appointmentsAdmin.complete': 'Completa', 'appointmentsAdmin.emptyTitle': 'Agenda libera', 'appointmentsAdmin.emptyText': 'Nessun appuntamento corrisponde a questa vista e ai filtri.', 'appointmentsAdmin.newEyebrow': 'NUOVA PRENOTAZIONE', 'appointmentsAdmin.createTitle': 'Crea appuntamento', 'appointmentsAdmin.customerName': 'Nome cliente', 'appointmentsAdmin.phone': 'Telefono', 'appointmentsAdmin.email': 'E-mail', 'appointmentsAdmin.service': 'Servizio', 'appointmentsAdmin.slotAvailable': 'Orario disponibile', 'appointmentsAdmin.noSlots': 'Nessun orario disponibile', 'appointmentsAdmin.create': 'Crea appuntamento', 'appointmentsAdmin.qrAlt': 'Codice QR del portale clienti', 'appointmentsAdmin.selfService': 'Self-service cliente', 'appointmentsAdmin.selfServiceText': 'Condividi il QR per consentire ai clienti di prenotare o mettersi in fila senza assistenza del personale.', 'appointmentsAdmin.downloadQr': 'Scarica QR', 'appointmentsAdmin.rescheduleEyebrow': 'RIPROGRAMMA', 'appointmentsAdmin.currently': 'attualmente {{date}}', 'appointmentsAdmin.newSlot': 'Nuovo orario', 'appointmentsAdmin.saveChange': 'Salva modifica', 'appointmentsAdmin.updated': 'Appuntamento aggiornato', 'appointmentsAdmin.updateError': 'Impossibile aggiornare l’appuntamento', 'appointmentsAdmin.created': 'Appuntamento creato', 'appointmentsAdmin.createError': 'Impossibile creare l’appuntamento', 'appointmentsAdmin.rescheduled': 'Appuntamento riprogrammato', 'appointmentsAdmin.rescheduleError': 'Impossibile riprogrammare l’appuntamento',
}

const ja: Dictionary = {
  'appointmentsAdmin.eyebrow': 'ハイブリッド予約', 'appointmentsAdmin.title': '予約スケジュール', 'appointmentsAdmin.lead': '週単位で整理し、理容師で絞り込み、ダッシュボードから予約を変更できます。', 'appointmentsAdmin.customerPortal': '顧客ポータル', 'appointmentsAdmin.lockedTitle': '予約とハイブリッドスケジュール', 'appointmentsAdmin.lockedText': '時間予約と来店順受付を組み合わせ、チームのスケジュールを管理できます。', 'appointmentsAdmin.controls': '予約コントロール', 'appointmentsAdmin.view': '予約表示', 'appointmentsAdmin.today': '今日', 'appointmentsAdmin.week': '週', 'appointmentsAdmin.date': '日付', 'appointmentsAdmin.barber': '理容師', 'appointmentsAdmin.status': 'ステータス', 'appointmentsAdmin.active': '有効',
  'appointmentsAdmin.status.Confirmed': '確定', 'appointmentsAdmin.status.CheckedIn': '受付済み', 'appointmentsAdmin.status.Completed': '完了', 'appointmentsAdmin.status.Cancelled': 'キャンセル', 'appointmentsAdmin.status.NoShow': '来店なし', 'appointmentsAdmin.daySummary': '選択日の予約', 'appointmentsAdmin.weekSummary': '選択週の予約', 'appointmentsAdmin.noContact': '連絡先未登録', 'appointmentsAdmin.reschedule': '日時変更', 'appointmentsAdmin.checkIn': 'チェックイン', 'appointmentsAdmin.cancel': 'キャンセル', 'appointmentsAdmin.complete': '完了', 'appointmentsAdmin.emptyTitle': '予約はありません', 'appointmentsAdmin.emptyText': 'この表示とフィルターに一致する予約はありません。', 'appointmentsAdmin.newEyebrow': '新規予約', 'appointmentsAdmin.createTitle': '予約を作成', 'appointmentsAdmin.customerName': '顧客名', 'appointmentsAdmin.phone': '電話番号', 'appointmentsAdmin.email': 'メール', 'appointmentsAdmin.service': 'サービス', 'appointmentsAdmin.slotAvailable': '利用可能な時間', 'appointmentsAdmin.noSlots': '空き時間なし', 'appointmentsAdmin.create': '予約を作成', 'appointmentsAdmin.qrAlt': '顧客ポータルのQRコード', 'appointmentsAdmin.selfService': '顧客セルフサービス', 'appointmentsAdmin.selfServiceText': 'QRコードを共有すると、スタッフを介さずに予約や順番待ちができます。', 'appointmentsAdmin.downloadQr': 'QRをダウンロード', 'appointmentsAdmin.rescheduleEyebrow': '日時変更', 'appointmentsAdmin.currently': '現在 {{date}}', 'appointmentsAdmin.newSlot': '新しい時間', 'appointmentsAdmin.saveChange': '変更を保存', 'appointmentsAdmin.updated': '予約を更新しました', 'appointmentsAdmin.updateError': '予約を更新できませんでした', 'appointmentsAdmin.created': '予約を作成しました', 'appointmentsAdmin.createError': '予約を作成できませんでした', 'appointmentsAdmin.rescheduled': '予約日時を変更しました', 'appointmentsAdmin.rescheduleError': '予約日時を変更できませんでした',
}

const ko: Dictionary = {
  'appointmentsAdmin.eyebrow': '하이브리드 예약', 'appointmentsAdmin.title': '예약 일정', 'appointmentsAdmin.lead': '주간 일정을 정리하고 바버별로 필터링하며 대시보드에서 예약 시간을 변경하세요.', 'appointmentsAdmin.customerPortal': '고객 포털', 'appointmentsAdmin.lockedTitle': '예약 및 하이브리드 일정', 'appointmentsAdmin.lockedText': '시간 예약과 현장 대기를 함께 운영하고 팀 일정을 관리하세요.', 'appointmentsAdmin.controls': '일정 제어', 'appointmentsAdmin.view': '일정 보기', 'appointmentsAdmin.today': '오늘', 'appointmentsAdmin.week': '주', 'appointmentsAdmin.date': '날짜', 'appointmentsAdmin.barber': '바버', 'appointmentsAdmin.status': '상태', 'appointmentsAdmin.active': '활성',
  'appointmentsAdmin.status.Confirmed': '확정', 'appointmentsAdmin.status.CheckedIn': '체크인', 'appointmentsAdmin.status.Completed': '완료', 'appointmentsAdmin.status.Cancelled': '취소', 'appointmentsAdmin.status.NoShow': '노쇼', 'appointmentsAdmin.daySummary': '선택한 날짜의 예약', 'appointmentsAdmin.weekSummary': '선택한 주의 예약', 'appointmentsAdmin.noContact': '연락처 없음', 'appointmentsAdmin.reschedule': '일정 변경', 'appointmentsAdmin.checkIn': '체크인', 'appointmentsAdmin.cancel': '취소', 'appointmentsAdmin.complete': '완료', 'appointmentsAdmin.emptyTitle': '예약 없음', 'appointmentsAdmin.emptyText': '현재 보기와 필터에 맞는 예약이 없습니다.', 'appointmentsAdmin.newEyebrow': '새 예약', 'appointmentsAdmin.createTitle': '예약 만들기', 'appointmentsAdmin.customerName': '고객 이름', 'appointmentsAdmin.phone': '전화번호', 'appointmentsAdmin.email': '이메일', 'appointmentsAdmin.service': '서비스', 'appointmentsAdmin.slotAvailable': '예약 가능 시간', 'appointmentsAdmin.noSlots': '예약 가능 시간 없음', 'appointmentsAdmin.create': '예약 만들기', 'appointmentsAdmin.qrAlt': '고객 포털 QR 코드', 'appointmentsAdmin.selfService': '고객 셀프서비스', 'appointmentsAdmin.selfServiceText': 'QR을 공유하면 고객이 직원 도움 없이 예약하거나 대기열에 참여할 수 있습니다.', 'appointmentsAdmin.downloadQr': 'QR 다운로드', 'appointmentsAdmin.rescheduleEyebrow': '일정 변경', 'appointmentsAdmin.currently': '현재 {{date}}', 'appointmentsAdmin.newSlot': '새 시간', 'appointmentsAdmin.saveChange': '변경 저장', 'appointmentsAdmin.updated': '예약이 업데이트되었습니다', 'appointmentsAdmin.updateError': '예약을 업데이트할 수 없습니다', 'appointmentsAdmin.created': '예약이 생성되었습니다', 'appointmentsAdmin.createError': '예약을 생성할 수 없습니다', 'appointmentsAdmin.rescheduled': '예약 시간이 변경되었습니다', 'appointmentsAdmin.rescheduleError': '예약 시간을 변경할 수 없습니다',
}

const zh: Dictionary = {
  'appointmentsAdmin.eyebrow': '混合预约', 'appointmentsAdmin.title': '预约日程', 'appointmentsAdmin.lead': '按周整理日程、按理发师筛选，并直接在管理面板中调整预约。', 'appointmentsAdmin.customerPortal': '客户门户', 'appointmentsAdmin.lockedTitle': '预约与混合日程', 'appointmentsAdmin.lockedText': '结合定时预约与到店排队，并管理团队日程。', 'appointmentsAdmin.controls': '日程控制', 'appointmentsAdmin.view': '日程视图', 'appointmentsAdmin.today': '今天', 'appointmentsAdmin.week': '本周', 'appointmentsAdmin.date': '日期', 'appointmentsAdmin.barber': '理发师', 'appointmentsAdmin.status': '状态', 'appointmentsAdmin.active': '有效',
  'appointmentsAdmin.status.Confirmed': '已确认', 'appointmentsAdmin.status.CheckedIn': '已签到', 'appointmentsAdmin.status.Completed': '已完成', 'appointmentsAdmin.status.Cancelled': '已取消', 'appointmentsAdmin.status.NoShow': '未到店', 'appointmentsAdmin.daySummary': '所选日期的预约', 'appointmentsAdmin.weekSummary': '所选周的预约', 'appointmentsAdmin.noContact': '未登记联系方式', 'appointmentsAdmin.reschedule': '改期', 'appointmentsAdmin.checkIn': '签到', 'appointmentsAdmin.cancel': '取消', 'appointmentsAdmin.complete': '完成', 'appointmentsAdmin.emptyTitle': '暂无预约', 'appointmentsAdmin.emptyText': '没有符合当前视图和筛选条件的预约。', 'appointmentsAdmin.newEyebrow': '新预约', 'appointmentsAdmin.createTitle': '创建预约', 'appointmentsAdmin.customerName': '客户姓名', 'appointmentsAdmin.phone': '电话', 'appointmentsAdmin.email': '邮箱', 'appointmentsAdmin.service': '服务', 'appointmentsAdmin.slotAvailable': '可用时间', 'appointmentsAdmin.noSlots': '暂无可用时间', 'appointmentsAdmin.create': '创建预约', 'appointmentsAdmin.qrAlt': '客户门户二维码', 'appointmentsAdmin.selfService': '客户自助服务', 'appointmentsAdmin.selfServiceText': '分享二维码，让客户无需员工协助即可预约或加入排队。', 'appointmentsAdmin.downloadQr': '下载二维码', 'appointmentsAdmin.rescheduleEyebrow': '改期', 'appointmentsAdmin.currently': '当前 {{date}}', 'appointmentsAdmin.newSlot': '新时间', 'appointmentsAdmin.saveChange': '保存更改', 'appointmentsAdmin.updated': '预约已更新', 'appointmentsAdmin.updateError': '无法更新预约', 'appointmentsAdmin.created': '预约已创建', 'appointmentsAdmin.createError': '无法创建预约', 'appointmentsAdmin.rescheduled': '预约已改期', 'appointmentsAdmin.rescheduleError': '无法调整预约时间',
}

export const appointmentsAdminSupplement: Record<OfficialLocale, Dictionary> = {
  'es-419': es, en, 'pt-BR': pt, fr, ht, de, it, ja, ko, 'zh-CN': zh,
}
